#!/usr/bin/env python

import cloudscraper
from bs4 import BeautifulSoup

url = "https://www.palmeiras.com.br/allianz-parque/"
scraper = cloudscraper.CloudScraper()
response = scraper.get(url).text
soup = BeautifulSoup(response, 'html.parser')

container = soup.find('div', class_ = 'header-tempo-real-campeonato')

def match(container):
    date = container.text.strip().split('\n')[8].replace(' |', '')
    time = container.text.strip().split('\n')[9]
    return date, time

def home_game(container):
    return container.select('span')[5].text.strip() == "ALLIANZ PARQUE"


if home_game(container):
    date = match(container)
    print('Vai ter jogo dia %s às %s, fera' %(date[0], date[1].strip()))
else:
    print('Próximo jogo será fora de casa, de boa')
